name: specifier
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tflite_v3:
    git:
      url: https://github.com/KumaloWilson/tflite_v3.git
      ref: main  # or a specific commit hash

  camera: ^0.11.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  uuid: ^4.5.1
  google_sign_in: ^6.3.0
  path: ^1.9.1
  firebase_storage: ^12.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  get: ^4.7.2
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  simple_animations: ^5.1.0
  supercharged: ^2.1.1
  http: ^1.3.0
  google_maps_flutter: ^2.12.0
  logger: ^2.5.0
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ai_model/
